AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/LineLength:
  Max: 120

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
