AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
