AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/LineLength:
  Max: 120

Style/HashSyntax:
  UseHashRocketsWithSymbolValues: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
