language: ruby
script:
  - bundle exec rspec
  - bundle exec rubocop
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9db7a73fbd8f58f1432
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
